// API

export enum EventTypeENUM {
  NGX_ACE_VALUE_CHANGE = 'NGX_ACE_VALUE_CHANGE',
  NGX_AGM_CORE_PLACES_CHANGE = 'NGX_AGM_CORE_PLACES_CHANGE',
  NGX_AGM_CORE_REVERSE_GEOCODE = 'NGX_AGM_CORE_REVERSE_GEOCODE',
  NAVIGATE = 'NAVIGATE',
}

export interface IEvent<T = any> {
  type: EventTypeENUM;
  payload?: T;
}
