export declare enum EventTypeENUM {
  INIT_DOM_EVENT_STATE = "INIT_DOM_EVENT_STATE",
  LAYOUT_NAV_ITEM_CLICK = "LAYOUT_NAV_ITEM_CLICK",
  LAYOUT_LOGO_CLICK = "LAYOUT_LOGO_CLICK",
  LAYOUT_HELP_MODULE_CLICK = "LAYOUT_HELP_MODULE_CLICK",
  LAYOUT_QUICK_MODULE_CLICK = "LAYOUT_QUICK_MODULE_CLICK",
  LAYOUT_SIDENAV_OPEN = "LAYOUT_SIDENAV_OPEN",
  LAYOUT_LANGUAGE_CHANGE = "LAYOUT_LANGUAGE_CHANGE",
  NGX_ACE_VALUE_CHANGE = "NGX_ACE_VALUE_CHANGE",
  NGX_AGM_CORE_PLACES_CHANGE = "NGX_AGM_CORE_PLACES_CHANGE",
  NGX_AGM_CORE_REVERSE_GEOCODE = "NGX_AGM_CORE_REVERSE_GEOCODE",
  NAVIGATE = "NAVIGATE"
}

export interface IEvent<T = any> {
  type: EventTypeENUM;
  payload?: T;
}
