// ANGULAR
import { Component, Input } from '@angular/core';

@Component({
  selector: 'lib-angular-material-icon-select',
  templateUrl: './angular-material-icon-select.component.html',
  styleUrls: ['./angular-material-icon-select.component.scss'],
})
export class AngularMaterialIconSelectComponent {
  @Input() icons: string[] = [
    'adjust',
    'admin_panel_settings',
    'apps',
    'check',
    'chat',
    'close',
    'code',
    'comment',
    'contacts',
    'dashboard',
    'dashboard_customize',
    'device_hub',
    'fingerprint',
    'home',
    'insights',
    'insert_chart_outlined',
    'local_library',
    'location_city',
    'lock',
    'mail',
    'manage_accounts',
    'map',
    'memory',
    'menu',
    'menu_open',
    'navigate_next',
    'palette',
    'person',
    'photo_album',
    'photo_library',
    'play_circle_outline',
    'preview',
    'public',
    'query_stats',
    'search',
    'security',
    'settings_applications',
    'star_border',
    'table_chart',
    'task',
    'thumb_up',
    'tty',
    'vertical_align_bottom',
    'visibility',
  ];
}
